version: '3'

tasks:
  default:
    deps:
      - client
      - runner
      - server

  client:
    cmds:
      - go build -o ./miso ./apps/cli

  runner:
    cmds:
      - go build -o ./miso-runner ./apps/runner

  server:
    cmds:
      - go build -o ./miso-server ./apps/server